version: '3.9'
services:
  backend:
    container_name: backend
    build: ./backend
    ports:
      - 3005:3005
    volumes:
      - ./backend:/backend
    environment:
      - DB_USER=root
      - DB_PASS=password
      - DB_HOST=db
      - DB_PORT=10000
    depends_on:
      - db
  db:
    image: mysql:8.0.21
    container_name: db
    platform: linux/x86_64
    ports:
      - 3306:10000
    environment:
      - MYSQL_ROOT_PASSWORD=password
