version: '3.9'
services:
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - 3000:3001
    volumes:
      - ./frontend:/frontend
    depends_on:
      - backend
  backend:
    container_name: backend
    build: ./backend
    ports:
      - 3005:3005
    working_dir: /backend
    command: npm run dev
    volumes:
      - ./backend:/backend
    environment:
      - PORT=3005
      - DB_USER=root
      - DB_PASS=password
      - DB_HOST=db
      - DB_PORT=3306
    depends_on:
      - db
  db:
    image: mysql:8.0.21
    container_name: db
    platform: linux/x86_64
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
