on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test_back:
    runs-on: ubuntu-latest
    steps:
      - name: Verifica o repositório do Git
        uses: actions/checkout@v2
      
      - name: Instala o node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Executando testes no Back End
        run: cd ./backend && npm install && npm test